### ISSUE TITLE
Add an "Again" button, to see the same card in the same session

### ISSUE THREAD

**Issue by shintoo** [fabd/kanji-koohii#184] opened 2020-12-27 05:10 UTC
## The Problem
It is necessary to have multiple review sessions in a day to realistically progress, even if the strategy of selecting "Hard" instead of "No" for forgotten Kanji is used (done after having set the "Maximum box for cards marked 'Hard'" value to 1). Seeing a forgotten Kanji just once a day is unlikely to help a user remember it the next day.

## Proposed Solution
Add an "Again" button to the review session view, that puts the card in box 1 *and* puts it in the back of the pile for the *same review*.

This would enable a more Anki-like review structure, as I'm sure many of us are already familiar with.

"Again" would put the card into the back of the current review session, and when the user sees it again, they can still select "again" continuously, until they finally select one of No/Hard/Yes/Easy. Also, selecting "Again" functions as a "No", i.e. that it fails the card and puts it into box 1. If the user hits "again" for a card, and then when they see it again in the same session, hits "yes", then that card would then move to box 2.

This could mess with the total remembered value that is reported after ending a review; I think it can just be counted as a failed card for that purpose.

Anki reviews are simple in that one can finish all of one's review for the day without leaving the review session. I have been using the technique of selecting "hard" instead of "no" for Kanji I have forgotten, to avoid the restudy process, but find myself not progressing, since I see the kanji once and then not again until the next day (at which I still don't remember it, ad infinitum).

A more involved change that prevents there being too many buttons on the review view would be an option in the settings, such as a checkbox for 'Replace "No" button with "Again" button'.

Especially since stories can already be viewed and edited during the review session, this will streamline the user experience a lot.

Thanks for considering!

**Comment by fabd** [comment] 2021-01-01 15:05
Hi shintoo,

Thanks for the suggestion. Yes, it would be good to streamline reviews.

Whether it provides something similar to Anki's "Learning" stage, I'm not sure : I've never used Anki but I see the docs mentions [steps](https://docs.ankiweb.net/#/studying?id=learning) of 1 and 10 minutes for Learning. I'm not sure how that works. How does Anki make you wait 10 minutes?

On Koohii say the user added 20 new cards. If they start a review of the blue pile they can either, mark most cards as hard/yes/easy given that they have already invested time in Study pages with the initial mnemonic. Or the user prefers the "Learning" stage way of Anki, in this case the user can edit the story with S shortcut, then select "Again", and cycle through the pile in several passes, marking them hard/yes/easy. 

I suppose even if there is no time (less than 1 day) in this Learning stage, if the user  picks "Hard" or "Yes" they can repeat this process for the cards soon (1 day, or 2-4 days). To repeat the process once a day for new cards then the user would have to make sure to pick "Hard" for any remembered kanji, until they are confident to let the card move up intervals.

I guess that could work. Any thoughts?

Still thinking about exact implementation. Leaning towards adding an option to SRS Settings  to _Use Learning mode (similar to Anki) : With this option enabled, the "No" button is replaced by "Again" (or "Repeat"). The "Again" answer moves the card to the back of the pile for another test in the same review session. If you end the session with the "End" button the "Again" cards default to a "Hard" answer and will be due again in the next day"._

Something like that. Main reason is to not disturb existing users though my hunch is most new users would prefer that option.

Also, I would probably add a "Send card to restudy pile" in the card's top right "hamburger menu". That way with "Learning" mode enabled, you can still use the Restudy pile.

**Comment by fabd** [comment] 2021-01-01 15:13
> Anki reviews are simple in that one can finish all of one's review for the day without leaving the review session

To me the implmentation sounds like it answers that , which is good. A definite improvement.

> It is necessary to have multiple review sessions in a day to realistically progress, (...)

I wouldn't say it's necessary from my experience (hardcore Heisig mnemonics approach, i finished RTK1 and could remember at least half the characters after a single initial review and a night's sleep), however I am guessing most users would prefer that.

This is another problem to solve.

If the user wants to manage 2-3 sessions in the day, then I guess the cards can NOT be marked as "hard" answers. If we do that, they are removed from the due pile.

To approximate the "learning" stage, on Koohii, then what we would do is "again" cards are not updated. Once the pile is only "again" cards, the review page would need to give a clear visual cue that there are only "again" cards left (hard to say without getting a feel for it). Then the user needs to "End" the review explicitly. In that case, the due pile remains available, with the cards that were not marked hard/yes/easy. And the user can repeat this process 2-3 times in the day if they wish.

**Comment by shintoo** [comment] 2021-01-03 06:09
Thanks for taking the time to reply, I'm delighted the idea is being considered!

> How does Anki make you wait 10 minutes?

Generally, if a card is due in 10 minutes, it will simply be put after some amount of 1-minute cards; there is no timer that makes the user wait. E.g. if there are simply two cards remaining, both due in 10 minutes, they will just be shown one after the other, no wait required.

> I suppose even if there is no time (less than 1 day) in this Learning stage, if the user picks "Hard" or "Yes" they can repeat this process for the cards soon (1 day, or 2-4 days). To repeat the process once a day for new cards then the user would have to make sure to pick "Hard" for any remembered kanji, until they are confident to let the card move up intervals.
> 
> I guess that could work. Any thoughts?

I think that works out okay. I also don't think it necessary to have the 1 minute/10 minute intervals, just simply the "Again" feature will serve that purpose.

> Still thinking about exact implementation. Leaning towards adding an option to SRS Settings to _Use Learning mode (similar to Anki) : With this option enabled, the "No" button is replaced by "Again" (or "Repeat"). The "Again" answer moves the card to the back of the pile for another test in the same review session. If you end the session with the "End" button the "Again" cards default to a "Hard" answer and will be due again in the next day"._

I like this, but one thing that comes to mind is if a user chooses to end a review half way through, with the intention of coming back later that day (if something comes up during review time, etc). Usually, if I am manually ending a review before it is complete, it's because I plan on finishing it later that day, not because I want that to be it for the day. 

It may make sense to just leave the "Again" cards as due until they are passed, and just let the already in-place system take care of the scheduling. One way to manage this is to mimic the restudy process: If Learning Mode is enabled, cards left as "Again" at the end of a review session will be put into box 1 and into the `learnedkanji` table, effectively being a relearned kanji ("No" -> Restudy -> "Add to learned list" button).

Thanks again, and happy new year!

**Comment by fabd** [comment] 2021-02-18 16:37
Looking into this now. In order to act on this issue I need to clarify the goals of the feature, and then the implementation.

I also need to revisit why I implemented the "Hard" answer to clear up some confusion I have.

Koohii's "Hard" answer (cf blog post [New : "Hard" rating for flashcard answers](https://kanji.koohii.com/news/id/270)) :

- (similar to Anki's  "Again") `Hard` should be used for cards not fully remembered or difficult to remember
- (similiar to Anki's "Again") `Hard` decreases the card's review interval (to see the card more frequently, albeit admittedly on Koohii the effect is muted unless user tweaks the "Max box for Hard answer" setting, while Anki also handles a special "lapsed" state)
- by design, `Hard` answers skip the Restudy (red) pile, cards in 1+ Review box rated `Hard` stay there with a fixed 1 day interval
- unlike Anki's "Again", `Hard` does not have "less than 1 day" intervals, and therefore, does not provide the ability to repeat cards in the same review session (where from what I understand, Anki would put the card at the back of the pile and show it again later in the same review session)

Some takeaways:

- there is some overlap between Koohii `Hard` and Anki's `Again' ratings in that both decrease the review interval
- however Anki's `Again` marks a card as "lapsed" (ie. forgotten) which is very roughly equivalent to Koohii's Restudy steps since they are both about handling _forgotten_ cards
- Anki's `Again` rating also has two modes : one in learning stage, and one in review stage (cf. [manual](https://apps.ankiweb.net/docs/manual20.html#learning)). Koohii doesn't handle separate stages, or rather the Restudy pile is the classic Koohii way of handling forgotten cards

Considerations:

- avoid displaying five buttons, keep things simpler, and also hard to squeeze them in mobile view
- a "learning" stage in the SRS more or less replaces the Restudy list, hence No and Again are exclusive

With that in mind, the main value for Koohii's SRS in my eyes is to provide something a little different, simple, with some good defaults, pre-built flashcards, and integration with the Study pages. It would be benficial to align with a popular program like Anki, in terms of user expectations, while Koohii can retain the simpler underpinnings (Leitner boxes)

As part of this issue I should also improve the SRS documentation.

Here is a draft of the three main ways of studying on Koohii. 1 and 2 already exist. 3 would be covered by this issue:

https://github.com/fabd/kanji-koohii/wiki/Spaced-Repetition-Documentation-update-(draft)

One question remains: should we also have learning stage? What would it look like?

If we go with Again / Hard / Yes / Easy, when user starts a new cards review, the Hard answer will use a fixed 1 day interval (as it works currently for New and "1+" cards). When selecting "Again" the card will be counted as forgotten, it will move to the 1+ box instead of staying in the new card pile, and will be due immediately (so it will show in the due cards review).

..hmm.. I suppose this works.. so for NEW cards and cards in box 1+ (reviewed in earlier days), using Again keeps card inm box1+ but also keeps showing as a due card until rated Hard/Yes/Easy. Cards answered Hard have a fixed 1 day minimum interval, but they are cleared of the due pile until tomorrow.

**Comment by fabd** [comment] 2021-03-25 10:47
Feedback from Joshua

> I really like the idea of the "again" button perhaps as an addition rather than replacement of "no" if all it does is throw the card back into the stack you're currently studying instead of a separate "restudy" list. Then the user can decide later if they want to designate it as "hard", "no" or "yes" later when it comes back.
> 
> For me it feels like less work to make a certain card repeat then to go through the whole "restudy" pack just to see the one card I wanted to a couple more times.
> 
> Ideally if I completely forgot a card, I would hit "again" then "no" then in the restudy "hard". I think that would be great

Here is a mockup of what a setting would look like in _Account Settings > Spaced Repetition_ :

![Screenshot from 2021-03-25 11-45-55](https://user-images.githubusercontent.com/169391/112460891-ac79b900-8d5f-11eb-81bd-096ee1312413.png)

is it clear to the user? 

Essentially the only purpose of this setting is to keep displaying 4 buttons instead of 5, particularly for phones portrait mode.

The setting just switches the RED button for whichever rating the user would use more often, but all ratings would remain available via shortcuts and the little dropdown menu on the flashcard.

**Closed** 2021-12-20 11:49 UTC
Labels: feature
